// Turns the plain-text stories in folktales/stories/<category>/ into
// folktales/stories.js, which folktales.html loads with a classic <script>.
// (A page opened by double-click can't fetch() local files in Chrome, so the
// text has to be baked into a script file.)
//
// Run after adding or editing a story:   node folktales/build-stories.mjs
//
// Story file format — NN-short-name.txt:
//   line 1      title (optional; if the first line reads like a sentence,
//               the title is made from the file name instead)
//   the rest    one paragraph per line; blank lines are ignored
//   "Moral: …" / "Teaching: …"  shown as the story's lesson
//   "Extra Information: …"      shown as a side note
// An image with the same name (.png/.jpg/.jpeg/.webp) becomes the illustration.
// A language code before .txt (e.g. 01-name.te.txt) is a translation; files
// without one are English.

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const STORIES_DIR = join(HERE, 'stories');
const OUT = join(HERE, 'stories.js');

// spec §8.2 order
const CATEGORIES = [
  'tenali-ramakrishna',
  'vikram-bhetal',
  'panchatantra',
  'paramanandayya-sishyulu',
  'freedom-fighter',
  'festival-stories',
];
const LANGS = ['en', 'hi', 'te', 'ta', 'kn', 'ml'];
const IMAGE_EXTS = ['png', 'jpg', 'jpeg', 'webp'];

const stripMarkdown = s => s
  .replace(/^#{1,6}\s*/, '')
  .replace(/\*\*(.+?)\*\*/g, '$1')
  .replace(/\*(.+?)\*/g, '$1')
  .replace(/^\*+|\*+$/g, '')
  .trim();

const tidy = s => s
  .replace(/([a-z”’)][.!?])([A-Z“‘])/g, '$1 $2') // "washerman.The" → "washerman. The"
  .replace(/\s{2,}/g, ' ')
  .trim();

const titleFromFile = base => base
  .replace(/^\d+-/, '')
  .split('-')
  .map(w => w.charAt(0).toUpperCase() + w.slice(1))
  .join(' ');

const looksLikeTitle = line => line.length <= 70 && !/[.!?,;:]$/.test(line);

function parseStory(text, base) {
  const lines = text.replace(/^﻿/, '').replace(/\r\n?/g, '\n')
    .split('\n').map(stripMarkdown).filter(Boolean);

  let title = titleFromFile(base);
  if (lines.length && looksLikeTitle(lines[0])) title = lines.shift();

  const paragraphs = [];
  let lesson = null;
  let note = null;
  for (const raw of lines) {
    const line = tidy(raw);
    const lessonMatch = line.match(/^(?:moral|teaching)\s*:\s*(.+)$/i);
    const noteMatch = line.match(/^extra information\s*:\s*(.+)$/i);
    if (lessonMatch) lesson = lessonMatch[1];
    else if (noteMatch) note = noteMatch[1];
    else paragraphs.push(line);
  }
  return { title, paragraphs, lesson, note };
}

const data = {};
for (const cat of CATEGORIES) {
  const dir = join(STORIES_DIR, cat);
  data[cat] = [];
  if (!existsSync(dir)) continue;

  const files = readdirSync(dir).filter(f => f.endsWith('.txt')).sort();
  const byBase = new Map();
  for (const file of files) {
    const m = file.match(/^(.+?)(?:\.([a-z]{2}))?\.txt$/);
    const base = m[1];
    const lang = m[2] && LANGS.includes(m[2]) ? m[2] : 'en';
    if (!byBase.has(base)) byBase.set(base, {});
    byBase.get(base)[lang] = file;
  }

  for (const [base, langFiles] of byBase) {
    const text = {};
    for (const [lang, file] of Object.entries(langFiles)) {
      const raw = readFileSync(join(dir, file), 'utf8');
      if (!raw.trim()) { console.warn(`! empty file skipped: ${cat}/${file}`); continue; }
      text[lang] = parseStory(raw, base);
    }
    if (!Object.keys(text).length) continue;

    const ext = IMAGE_EXTS.find(e => existsSync(join(dir, `${base}.${e}`)));
    data[cat].push({
      id: `${cat}/${base}`,
      image: ext ? `folktales/stories/${cat}/${base}.${ext}` : null,
      text,
    });
  }
}

writeFileSync(OUT,
  '// Generated by folktales/build-stories.mjs — edit the .txt files, not this.\n'
  + `window.FOLKTALES = ${JSON.stringify(data, null, 2)};\n`);

for (const cat of CATEGORIES) {
  console.log(`${cat}: ${data[cat].map(s => s.text.en?.title ?? Object.values(s.text)[0].title).join(' | ') || '(none)'}`);
}
