// Generated by folktales/build-stories.mjs — edit the .txt files, not this.
window.FOLKTALES = {
  "tenali-ramakrishna": [
    {
      "id": "tenali-ramakrishna/01-The-Handful",
      "image": "folktales/stories/tenali-ramakrishna/01-The-Handful.png",
      "text": {
        "en": {
          "title": "The Handful of Grain and Coins",
          "paragraphs": [
            "In the Vijayanagara Kingdom, a proud woman named Vidhyulatha claimed that no one could match her wit and intelligence. She put up a board offering 1,000 gold coins to anyone who could outsmart her.",
            "Many scholars tried but failed. One day, a firewood seller came to her door and offered his firewood in exchange for a “handful of grain.”",
            "Vidhyulatha agreed, but after the firewood was delivered, the seller insisted that she had misunderstood his words. He explained that he meant a single grain large enough to fill a hand. Since she could not give him exactly what he had asked for, he claimed that she had lost the challenge and demanded the 1,000 gold coins.",
            "Vidhyulatha angrily argued with him, and the matter was taken to the provincial court. After hearing both sides, the judge agreed that the seller had outwitted her through the clever wording of his demand.",
            "Vidhyulatha had to take down her challenge board and pay the promised reward. Curious about how a simple firewood seller had defeated her, she asked who he really was.",
            "The man removed his disguise. He was none other than Tenali Raman, who had cleverly taught her a lesson in humility."
          ],
          "lesson": "Be humble about your talents and abilities.",
          "note": null
        }
      }
    },
    {
      "id": "tenali-ramakrishna/02-The-Biggest-Fool",
      "image": "folktales/stories/tenali-ramakrishna/02-The-Biggest-Fool.png",
      "text": {
        "en": {
          "title": "The Biggest Fool in the Kingdom",
          "paragraphs": [
            "King Krishnadevaraya loved horses. One day, a trader showed him a magnificent Arabian horse and claimed that he had two more like it back in Arabia.",
            "Impressed by the horse, the King paid the trader 5,000 gold coins in advance for the other two. The trader promised to return within two days, but weeks passed and he never returned.",
            "One evening, the King saw Tenali Raman writing a list. Curious, he asked what it was. Tenali revealed that it was a list of the biggest fools in the Vijayanagara Kingdom, with the King’s name at the top.",
            "The King was furious and demanded an explanation. Tenali replied, “You trusted a stranger and gave him 5,000 gold coins without any guarantee that he would return. That makes you the biggest fool.”",
            "The King then asked, “But what if the trader actually comes back with the horses?”",
            "Tenali smiled and said, “Then I shall remove your name and put his at the top. He would be the bigger fool!”",
            "The King understood Tenali’s clever lesson."
          ],
          "lesson": "Never trust strangers blindly, especially when money is involved.",
          "note": null
        }
      }
    }
  ],
  "vikram-bhetal": [
    {
      "id": "vikram-bhetal/01-The-Three-Suitors",
      "image": "folktales/stories/vikram-bhetal/01-The-Three-Suitors.png",
      "text": {
        "en": {
          "title": "The Three Suitors",
          "paragraphs": [
            "King Vikramaditya was walking through a dark cremation ground with Betal’s corpse over his shoulder when the ghost began telling him a tale.",
            "Once, a beautiful princess suddenly fell ill and died before she could be married. Three princes who loved her arrived too late, but each used his special skill to help bring her back.",
            "The first prince, skilled in mystical arts, created a magical flying chariot and took them to the princess’s resting place. The second prince, a master physician, used magical herbs and mantras to restore her life. The third prince, a great warrior, defeated the demons and bandits guarding the royal vault.",
            "When the princess was alive again, all three princes claimed that they deserved to marry her. Each argued that she would still be dead without his contribution.",
            "Betal then asked Vikramaditya, “Who truly deserves her hand?”",
            "Vikramaditya replied, “The warrior acted as her protector, while the first prince merely transported them. But the physician who restored her life took the role of a father or creator. Therefore, the other two princes may rightfully seek her hand.”",
            "As soon as Vikramaditya spoke, Betal laughed and flew back to his tree, forcing the King to begin his journey once again."
          ],
          "lesson": "Actions carry different weight depending on the role, intention, and responsibility behind them.",
          "note": null
        }
      }
    },
    {
      "id": "vikram-bhetal/02-The-Sacrifice",
      "image": "folktales/stories/vikram-bhetal/02-The-Sacrifice.png",
      "text": {
        "en": {
          "title": "The Sacrificing Mother and Son",
          "paragraphs": [
            "King Vikramaditya returned to the tree, lifted Betal onto his shoulder, and continued walking through the night. To test the King once again, Betal began another tale.",
            "Once, a king and his loyal minister visited a temple of Goddess Kali to pray for the safety of their kingdom. A divine voice declared that the minister and his only son must sacrifice themselves to save the kingdom.",
            "The devoted son immediately sacrificed his life. Unable to bear the loss of his son, the grieving minister followed him. The king, overcome with guilt, was about to sacrifice himself as well when Goddess Kali appeared and stopped him.",
            "Pleased by the king's devotion, the goddess granted him a boon. The king asked her to restore the minister and his son to life. She agreed.",
            "In his excitement, the king accidentally placed their heads on the wrong bodies. Both men came back to life, but with each other's heads.",
            "Betal then asked Vikramaditya, “Who are they now, and how should their relationships be understood?”",
            "The King replied, “A person's identity and consciousness belong to the head. Therefore, the man with the minister's head remains the minister, while the man with the son's head remains the son.”",
            "Satisfied with the King's answer, Betal laughed and disappeared into the night."
          ],
          "lesson": "When emotions create confusion, clear reasoning can help resolve even the most difficult problems.",
          "note": null
        }
      }
    }
  ],
  "panchatantra": [
    {
      "id": "panchatantra/01-The-Clever-Monkey",
      "image": "folktales/stories/panchatantra/01-The-Clever-Monkey.png",
      "text": {
        "en": {
          "title": "The Monkey and the Crocodile",
          "paragraphs": [
            "A long time ago, there was a monkey who lived in a rose-apple tree by the side of a river. He lived alone, but was very happy.",
            "One day, a crocodile came out of the river. He swam up to the tree and told the monkey that he had travelled a long distance and was in search of food as he was very hungry. The kind monkey offered him a few rose apples. The crocodile thanked him and asked him if he could visit the monkey again.",
            "“You are always welcome,” said the monkey.",
            "After that, the crocodile started visiting the monkey every day. They would share rose-apples and talk about everything they knew. The crocodile told the monkey that he had a wife and that they lived on the other side of the river. So the generous monkey plucked many rose-apples and gave them to the crocodile for his wife.",
            "The crocodile’s wife loved the rose-apples, but she grew jealous of her husband spending so much time away from her, in the company of his new friend. She pretended as if she did not believe that her husband, a crocodile, could be friends with a monkey. The crocodile convinced her of his friendship with the monkey.",
            "The crocodile’s wife thought to herself, “If the monkey eats only these sweet rose-apples, his flesh must be sweet too. He would be a delicious dinner.”",
            "So she asked her husband to invite his friend home so that she could meet him. But the crocodile was not happy about inviting his friend home. So the wife thought of a plan. She pretended to be very ill and told the crocodile that the doctor had said that she could get well only if she ate a monkey’s heart. If her husband wanted to save her life, he must bring her his friend’s heart.",
            "The crocodile was stupid enough to believe his wife. But the thought of killing his friend made him very unhappy. He did not want to harm his friend. At the same time, he did not want his wife to die.",
            "So the crocodile went to the rose apple tree and invited the monkey home to meet his wife. The monkey was very happy and readily agreed. The crocodile told the monkey that he could ride across the river to the other bank on his back. On reaching the middle of the river, the crocodile began to sink. The frightened monkey asked him why he was doing so.",
            "“I want to kill you.” said the crocodile. “My wife is ill and she can recover only if she eats a monkey’s heart.”",
            "The monkey was shocked and started thinking fast. He told the crocodile that he would gladly give up his heart to save the life of the crocodile’s wife, but he had left his heart behind in his tree. He requested the crocodile to turn back quickly so he could fetch his heart.",
            "The stupid crocodile became happy when he heard that the monkey was kind enough to offer his heart without any resistance. He couldn’t believe that the monkey was willing to offer his heart without any resistance. The thought of not killing his friend while proving his love towards his wife made him happy.",
            "The crocodile turned back and swam as fast as he could to the tree.",
            "When they reached, the monkey climbed up the tree to safety. He looked down at the crocodile and said, “Now you can go back to your wicked wife and tell her that her husband is the biggest fool in this world. Your foolishness has no parallel. You were ready to take my life because of an unjust demand from your wife. Then you were stupid enough to believe me and brought me back to the tree.”"
          ],
          "lesson": "A wise enemy is better than a foolish friend.",
          "note": null
        }
      }
    },
    {
      "id": "panchatantra/02-The-Blue-Jackal",
      "image": "folktales/stories/panchatantra/02-The-Blue-Jackal.png",
      "text": {
        "en": {
          "title": "Blue Jackal",
          "paragraphs": [
            "In a jungle, there lived a jackal. One day, looking for food, he wandered into a nearby village. A pack of dogs saw him and surrounded him. They attacked him and tried to drive him away. In order to save himself, the jackal ran into a nearby house. This house belonged to a washerman. The front yard of the washerman’s house was full of big vats. The jackal jumped into one of these vats to hide himself. The dogs followed him but could not find him anywhere and went away. After a while, the jackal came out of the vat. What he did not realize was that the vat in which he had hidden was full of blue dye and now his whole body was dyed blue. When the dogs saw him, they did not recognize him. Instead they thought it was some strange animal and ran away terrified.",
            "The jackal went back to the forest. Everywhere he went the animals would run away from him. The jackal could not understand why all the animals were so terrified of him all of a sudden. He went to the river and looked at his reflection. When he saw that he had been colored blue by the dye, he understood that all the animals were running away from him because they were terrified. He called out to them, “Friends! Do not be afraid of me. The Creator of this jungle, the Almighty God has sent me to be your king. I am here to protect you. Do not fear me.”",
            "The other animals were convinced and obeyed every instruction the jackal gave them. First he made them chase away all the other jackals from the forest. Next they were to hunt and bring him food everyday. The jackal lived this way for some days.",
            "One day, when he was sitting surrounded by all the other animals, he heard a pack of jackals howling in the distance. Having been away from others of his kind for so long, he was overcome with joy at hearing other jackals. He raised his head and howled in response. Hearing him, all the other animals realized that they had been fooled by an ordinary jackal. They all attacked him and tore him to pieces."
          ],
          "lesson": "The true nature of a man cannot be hidden for long.",
          "note": null
        }
      }
    }
  ],
  "paramanandayya-sishyulu": [
    {
      "id": "paramanandayya-sishyulu/01-The-Needle",
      "image": "folktales/stories/paramanandayya-sishyulu/01-The-Needle.png",
      "text": {
        "en": {
          "title": "The Seven Naive Disciples",
          "paragraphs": [
            "Guru Paramanandayya once needed a needle to mend his torn clothes. He sent his seven naive disciples to his friend Ramiah in the nearby village of Rapur to fetch one.",
            "On their way, they came across a flooded stream. One disciple said, “The stream is angry and will eat us if we cross now. Let us wait until it falls asleep at night.” The others agreed and waited until evening. When the water became calm, they crossed silently, believing the stream was asleep.",
            "They reached Rapur at midnight and asked Ramiah for a needle. When he gave it to one disciple, the others objected. “Give it to all of us equally. Otherwise, we may quarrel!”",
            "Ramiah explained that he had only one needle, but the disciples refused to accept it. His wife then pointed to a large wooden log and said, “Pin the needle to the log and carry it together.”",
            "The disciples happily followed her advice. Six carried the heavy log while the seventh carefully pinned the needle to it. They hurried back, worried that the stream might wake up.",
            "When they reached home, they proudly presented the log to Guru Paramanandayya. The Guru scolded them for their naivety.",
            "Soon, heavy rain made the firewood in the backyard useless. The disciples chopped the log into pieces, which were then used as firewood to cook their meal.",
            "Guru Paramanandayya smiled. Their naivety had finally served a useful purpose."
          ],
          "lesson": "Even a naive act can sometimes lead to a useful result.",
          "note": null
        }
      }
    },
    {
      "id": "paramanandayya-sishyulu/02-Pearls-Of-Laughter",
      "image": "folktales/stories/paramanandayya-sishyulu/02-Pearls-Of-Laughter.png",
      "text": {
        "en": {
          "title": "The Seven Naive Disciples and the Pumpkin",
          "paragraphs": [
            "Once Guru Paramanandayya needed a white pumpkin for a religious ceremony. He sent his seven naive disciples to a nearby garden to buy one.",
            "The gardener asked for one rupee. Just as one disciple was about to pay, the others suggested that they rest under a coconut tree first.",
            "Soon, the gardener’s daughter Padma came by and asked, “Father, which of the seven will buy the pumpkin?”",
            "Hearing this, the disciples became excited. Each one thought Padma had smiled at him. They began arguing over whom she had smiled at, showing off their hair tufts and trying to impress her. Their antics made Padma laugh even more.",
            "The gardener, amused by the scene, said that only Guru Paramanandayya could explain the reason for his disciples’ behavior. One disciple rushed to fetch the Guru.",
            "Paramanandayya arrived and apologized for his disciples’ naivety. Just then, a handsome local chieftain saw Padma laughing. Captivated by her beautiful smile, he asked her father for her hand in marriage.",
            "The gardener happily agreed. He thanked Paramanandayya, saying that his disciples’ antics had made Padma laugh and brought her this good fortune.",
            "The chieftain also rewarded the Guru, and Paramanandayya was delighted that his disciples’ naivety had once again brought an unexpected blessing."
          ],
          "lesson": "Sometimes, unexpected actions can lead to unexpected good fortune.",
          "note": null
        }
      }
    }
  ],
  "freedom-fighter": [
    {
      "id": "freedom-fighter/01-Shivaji-Afzal-Khan",
      "image": "folktales/stories/freedom-fighter/01-Shivaji-Afzal-Khan.png",
      "text": {
        "en": {
          "title": "Shivaji Maharaj and Afzal Khan",
          "paragraphs": [
            "Once Chhatrapati Shivaji Maharaj needed to protect his growing kingdom from the Bijapur Sultanate. He agreed to meet their powerful general Afzal Khan for a peace talk at Pratapgad Fort.",
            "Afzal Khan demanded Shivaji’s surrender and believed he had the upper hand. During their meeting, he suddenly attacked Shivaji with a hidden dagger. But Shivaji was protected by concealed armor and survived the attack.",
            "Afzal Khan’s bodyguard rushed forward to kill him, but Commander Jiva Mahala quickly struck down the attacker and protected Shivaji.",
            "At the signal, the hidden Maratha forces launched a surprise attack on Afzal Khan’s army. Without their leader, the Bijapur forces were defeated and fled.",
            "Shivaji Maharaj thanked his commanders for their courage and quick action. His careful preparation and strategy had protected his kingdom from a powerful enemy."
          ],
          "lesson": "Careful preparation and clever strategy can overcome overwhelming force.",
          "note": null
        }
      }
    },
    {
      "id": "freedom-fighter/02-The-Disguise",
      "image": "folktales/stories/freedom-fighter/02-The-Disguise.png",
      "text": {
        "en": {
          "title": "Bhagat Singh’s Great Escape",
          "paragraphs": [
            "After the assassination of British police officer John P. Saunders in Lahore on December 17, 1928, Bhagat Singh needed to escape before the police could capture him.",
            "Durgawati Devi, popularly known as Durga Bhabhi, devised a clever plan. Bhagat Singh cut his hair, shaved his beard, and dressed in a Western suit and hat so that the police would not recognize him.",
            "Durga Bhabhi pretended to be his wife and carried her young son, Sachindranath, creating the appearance of a respectable family. Shivaram Rajguru disguised himself as their servant and carried their luggage.",
            "The group walked through the heavily guarded Lahore railway station and boarded a first-class train. Chandrasekhar Azad travelled separately, disguised as a religious ascetic, ready to help if necessary.",
            "The disguises worked. The group safely travelled onward, changing trains and eventually reaching Calcutta.",
            "The daring escape became an example of courage, quick thinking, and careful planning during the Indian freedom struggle."
          ],
          "lesson": "Courage combined with careful planning can help overcome difficult challenges.",
          "note": null
        }
      }
    }
  ],
  "festival-stories": [
    {
      "id": "festival-stories/01-Naga-Panchami",
      "image": "folktales/stories/festival-stories/01-Naga-Panchami.png",
      "text": {
        "en": {
          "title": "Naga Panchami",
          "paragraphs": [
            "On the fifth day of the month of Shravan comes the festival of Nag Panchami. Cobras are worshipped on this day. This day is also called Garud Panchami. Ploughing of fields, peeling and cutting of vegetables etc. are prohibited on the occasion of this festival. There is a story behind it.",
            "They say that many a year ago there lived a farmer in a village. He went to plough his fields on the day of Nag Panchami. After working for a period he sat to take a little rest. Meanwhile his eight-year-old son also reached there. They began to gossip. The farmer again resumed his work. He was so much charmed by his son’s lovely talks that he could not see the hole of a snake, which was in the way of his plough. The plough destroyed the hole and its sharp pointed cutter killed the baby snakes in it.",
            "The snake returned to its hole after a little while and got very angry when it saw the dead baby snakes. The plough was lying there which had the baby snakes’ blood on it. The snake very easily understood who was the murderer of its babies. It immediately bit the farmer and his son. But this would not stop its anger.",
            "It reached the farmer’s house where his wife was busy in worshipping the ‘Nag Devta’. The snake thought to bite her after she had finished her prayers.",
            "The hungry snake then saw a bowl full of milk lying there and drank up all the milk. The farmer’s wife opened her eyes after the prayers and found the cobra physically present there and bowed to it. It was difficult for the snake to bite her, but it told her that it had bitten her husband and son to death.",
            "The farmer’s wife wept bitterly and asked for pardon. The snake thought that the farmer had killed its babies unknowingly, but on the other hand it had killed the farmer and his son in all its senses.",
            "It said to the farmer’s wife, “Come! I’ll suck all the poison out of the bodies of your husband and son.” The farmer’s wife hurried to the fields with the snake. The snake sucked up all the poison from the bodies of the farmer and his son. Both of them stood up in a little while. All of them bowed to the snake which later disappeared. That day onwards this tradition is on."
          ],
          "lesson": null,
          "note": null
        }
      }
    },
    {
      "id": "festival-stories/02-Bathukamma",
      "image": "folktales/stories/festival-stories/02-Bathukamma.png",
      "text": {
        "en": {
          "title": "Bathukamma",
          "paragraphs": [
            "In a peaceful village, there once lived seven brothers, each with a deep affection for their younger sister. From a young age, they pampered her with love and care, treasuring her above all else. As time passed, the brothers married and welcomed their wives into their lives, hoping for a harmonious family.",
            "However, as fate would have it, the wives grew envious of the sister’s radiant personality and the adoration she received from the village. This envy turned into resentment, and they became determined to diminish her light.",
            "One dreadful day, when the brothers were away on a hunting expedition, the wives seized the opportunity to confront the sister, intending to inflict emotional pain with their hurtful words. Unable to bear the hurtful words and realising that they had hated her for a long time, she ran away from the house and attempted to drown herself in a nearby lake.",
            "Her body turned into flowers in the water, and these flowers became the main component used to make Bathukamma.",
            "After her death, the brothers decided to turn this tragic event into a large festival each year. This coincided with the harvest time in Telangana, when the region experienced its biggest harvest of nine essential grains known as Navadhanya. Since the harvest time falls around Navratri, this vibrant floral festival is celebrated during this period.",
            "At the end of every night, after playing Bathukamma, the flowers are returned to the water, symbolising that even she must return to her fate."
          ],
          "lesson": null,
          "note": "The literal translation of Bathukamma means “live, O mother.” “Amma” is a term commonly used to address any woman with respect."
        }
      }
    }
  ]
};
